### ISSUE TITLE
One more alternative for the readme

### ISSUE THREAD

**Issue by Vampire** [cashapp/exhaustive#16]
I have two more alternative, you might consider adding to the readme:
```kotlin
when (...) {
    ...
}.let { /* it be exhaustive */ }
```
The only con I see from your other points is the locality.
This variant does not need a library or plugin, does not pollute the `Any` namespace and does not impact runtime performance as it is an inlined no-op.

and
```kotlin
Do exhaustive when (...) {
    ...
}
```
with an object and an infix function. There locality is better but it cannot be inlined to a no-op like the `let` solution.

**Comment by JakeWharton** [comment]
I don't think either of these are meaningfully different than what we have.

`let` is covered by https://github.com/cashapp/exhaustive#built-in-trailing-property-or-function-call which talks about a built-in function. Yes `let` (or any of these style `run`/`apply`/etc.) are good versions since you don't actually end up calling anything.

`Do exhaustive` is the same thing as https://github.com/cashapp/exhaustive#library-leading-expression except we use `exhastive` for the object and a binary minus function instead of an infix one.

Ultimately this whole repo is going to be deprecated in six months or so since Kotlin announced they'll be including `sealed when` support, otherwise I might add these additional variants of the existing alternatives since there are quite a few. Although at this point it's probably taken more work to write this comment but I already did that so I'm sticking with it.
