### ISSUE TITLE
Opt-out mechanism or class-based annotation?

### ISSUE THREAD

**Issue by ZacSweers** [cashapp/exhaustive#3]
Right now it's opt-in. Would it be feasible to support an opt-out approach instead? Or an annotation on the enum/sealed class itself like `@MustBeExhaustive` so all users of it use it rather than need to remember to opt in.

**Comment by JakeWharton** [comment]
It is feasible but complicated which is why it was not chosen for the initial approach.

Exhaustiveness checking can only be done on certain subject types. If you change that subject type you may no longer be subject to checking.

With an explicit annotation, we can fail in that case and allow you to make a decision as to whether the change was intentional or whether you want to switch to using an `else` (or simply go non-exhaustive).

Without an explicit annotation we have a choice:
 1. Require non-applicable types to opt-out explicitly
 2. Allow switching from applicable to non-applicable types without any indication

Option 1 seems the obvious choice here, but it's unclear whether that will be annoying in practice or not. It will be needed for _a lot_ of whens.

It also gets weird with subject-less when's in statement form. Do we require those to be annotated? There starts to be an asymmetry as to what needs annotated and when exhaustiveness applies in the opt-out case.

For this reason, it felt like the first draft should be opt-in. I'm not married to it, but it has far simpler semantics when you're learning about how it behaves.

**Comment by JakeWharton** [comment]
Another reason: the language is likely to make the feature opt-in and we want to track it as closely as possible in the interim.

**Comment by JakeWharton** [comment]
Deferring to the language: https://blog.jetbrains.com/kotlin/2021/05/nine-highlights-from-the-kotlin-roadmap/#sealed-whens
